### PR TITLE
include cc-by 4.0 license for documentation 

### LINKED ISSUE #175: License for the documentation?
The loo repo has only GPL-3 license. @aloctavodia asked to re-use LOO glossary. Maybe we should add also explicit CC license for the text content? Stan manual is with CC-BY ND 4.0 license. What do you think? Ping @jgabry

### PR DESCRIPTION
**Pull request by jgabry**
closes #175

@avehtari Do you know if we need to get permission from everyone who has contributed to the doc?

### CODE REVIEW

**Comment by avehtari** [comment]
> Do you know if we need to get permission from everyone who has contributed to the doc?

That is the best option. We don't need to ask if someone contributed only minor edits. That should leave quite small number of contributors (mainly vignette contributors).

**Comment by jgabry** [comment]
Ok. This might need to wait for the next release if it takes some time to get everyone to respond. But I'll start by tagging everyone here and then we can follow up with emails if necessary.

**Comment by jgabry** [comment]
Besides me and @avehtari I think the main contributors to the documentation have been: @paul-buerkner @MansMeg @topipa @LeeviLindgren @yao-yl @bnicenboim 

Are you all ok with updating the license to use cc-by 4.0 for the documentation? 


> That should leave quite small number of contributors (mainly vignette contributors).

We probably need to include anyone who wrote a lot of function documentation in addition to contributors to vignettes, but even still it's not many people.

**Comment by jgabry** [comment]
@MansMeg @paul-buerkner @topipa @LeeviLindgren @bnicenboim @yao-yl 
Do you agree to using the CC-BY 4.0 license for loo package documentation? 

(I went through https://github.com/stan-dev/loo/graphs/contributors and these seem like people who have made nontrivial contributions to the documentation, including function documentation and vignettes)

**Comment by LeeviLindgren** [comment]
Ok for me

**Comment by bnicenboim** [comment]
ok for me as well

**Comment by jgabry** [comment]
> @MansMeg @paul-buerkner @topipa @LeeviLindgren @bnicenboim @yao-yl Do you agree to using the CC-BY 4.0 license for loo package documentation?
> 
> (I went through https://github.com/stan-dev/loo/graphs/contributors and these seem like people who have made nontrivial contributions to the documentation, including function documentation and vignettes. @avehtari and I already agree to the change)

**Comment by paul-buerkner** [comment]
Yes I agree.

Jonah Gabry ***@***.***> schrieb am Mi., 29. März 2023, 21:57:

**Comment by topipa** [comment]
> @MansMeg @paul-buerkner @topipa @LeeviLindgren @bnicenboim @yao-yl Do you agree to using the CC-BY 4.0 license for loo package documentation?

Yes, agreed.

**Comment by jgabry** [comment]
Just noticed I forgot about this. I think I now have everyone's approval either here or by email, so I'll go ahead and merge this.

**Pull request merged**
