### PR TITLE
 stacking and Pseudo-BMA

### PR DESCRIPTION
**Pull request by yao-yl**
` model_weights (log_lik_list, method="stacking",BB=T,BB_n=1000, alpha=1, seed=NULL, optim_method="BFGS") `
is the function that calculates the weights of 
(1)stacking of predictive distributions ( `method="stacking"`) 
(2)or Pseudo-BMA (`method="pseudobma", BB=F`) 
(3)or Pseudo-BMA+ (`method="pseudobma", BB=T`).
where the input `log_lik_list` is a list of log likelihood matrixes without running leave-one-out.
Users can also specify the choice of BB sample size, Dirichlet shape parameter, random seed and choice of the optimization method.

Alternatively, users can obtain the leave-one-out matrixes by running exact LOO in advance. They can then use functions 
`pseudobma_weight (lpd_point, BB_n=1000, alpha=1, seed=NULL)`
or 
`stacking_weight( lpd_point, optim_method="BFGS")`
to get the Pseudo-BMA+ or stacking weights.

Here is an example that we are averaging 6 linear regression models Y= beta X.  Model i corresponds to the univariate regression with the  i-th covariate. 
```r
library(rstan)
library(loo)
code="
data{
int n;
int p;
vector[n] y;
matrix[n, p] X;
}
parameters{
vector[p] beta;
real<lower=0> sigma;
}
transformed parameters{
vector[n] theta;
theta= X * beta ;
}
model{
y~normal(theta, sigma);
beta~normal(0,  5);
sigma~gamma(0.1,0.1);
}
generated quantities {
vector[n] log_lik;
for (i in 1:n)
log_lik[i] = normal_lpdf(y[i] |theta[i], sigma);
}
"
n<-40
X<-rnorm(n*6,10,1)
X<-matrix(X, n,6)
y<-(X%*%c(2.6,2,3,3,2.5,2))+rnorm(n,0,1)
compile<- stan(model_code=code, data=list(y=as.vector(y), X=X[,1:2], n=length(y), p=2), iter=10)
K<-6
lpd_point<-matrix(NA, n,K)
log_lik_list<-list()
for(k in 1:K){  
  # Fit the k-th model with Stan. The  k-th model  is a univariate regression with X_k.
  fit<- stan(model_code=code, data=list(y=as.vector(y), X=as.matrix(X[,k]), n=length(y), p= 1), fit=compile)
  log_lik_list[[k]]<- extract(fit)[["log_lik"]]
  log_likelihood<-extract(fit)[['log_lik']]
  L<-loo(log_likelihood)
  lpd_point[,k]<-  L$pointwise[,1]
}
library("loo") 
#  log_lik_list is the pointwise liklihood list. 
model_weights (log_lik_list, method="pseudobma",BB=F)
model_weights (log_lik_list, method="pseudobma",BB=T)
model_weights (log_lik_list, method="stacking", optim_method="BFGS") 

# Alternatively, calcualte the leave one out likelihood first.
stacking_weight(lpd_point)
pseudobma_weight(lpd_point, BB=T) 
 ```

### CODE REVIEW

**Comment by jgabry** [comment]
I still haven't had a chance to look at this but it's fine to put it on
master if you need to for the paper. I can make edits if necessary before
we release it on CRAN.

**Comment by jgabry** [comment]
This is failing the checks on travis. @yao-yl can you take a look at the errors/warnings here https://travis-ci.org/stan-dev/loo/jobs/220371057 and see if you can fix them. If not let me know and I can help you do it.

**Comment by jgabry** [comment]
Hey Yuling, did you push those changes to GitHub? I don't see them.

**Comment by yao-yl** [comment]
Hi Jonah,  Yes, there should be an update in bb-stacking.R and NAMESPACE.

**Comment by jgabry** [comment]
Before we release this on CRAN we need tests for all of the new functionality (like the ones currently in the `tests` directory) but I will merge this into master now so it is easier for people to download the version corresponding to your paper. Also I didn't see any reference to the paper anywhere in the new documentation so that should be added to at some point.

**Comment by avehtari** [comment]
> Before we release this on CRAN we need tests for all of the new functionality (like the ones currently in the tests directory) but I will merge this into master now so it is easier for people to download the version corresponding to your paper. Also I didn't see any reference to the paper anywhere in the new documentation so that should be added to at some point.

@jgabry, @yao-yl  are these still missing?

**Pull request merged**
