### PR TITLE
Deprecate loo.cores in favour of mc.cores

### PR DESCRIPTION
**Pull request by cfhammill**
deprecate `loo.cores` as discussed in #53

### CODE REVIEW

**Comment by jgabry** [comment]
Looks good! Thanks for doing this. Can you update it one more time from the `new-psis` branch and fix that one merge conflict and then I'll get this merged?

**Comment by jgabry** [comment]
@cfhammill Thanks again for the PR. Can you regenerate the `model_weights.Rd` file that seems to be the issue? I think then I can just merge this.

**Comment by cfhammill** [comment]
Yup no problem, should be up now

**Comment by jgabry** [comment]
Merged. Thanks again!

**Comment by cfhammill** [comment]
Awesome, no problem!

**Pull request merged**
