### PR TITLE
add LFO vignette

### PR DESCRIPTION
**Pull request by paul-buerkner**
This PR adds a vignette about leave-future-out cross-validation based on our case study.

### CODE REVIEW

**Comment by avehtari** [comment]
Is this the same as in html in m-step repo? No need to knit this version?

**Comment by paul-buerkner** [comment]
I also have the knitted version ready on a branch, but it seems as if the loo master branch contains no knitted version of any vignette. That's why I didn't include it. Would love to have @jgabry in this discussion to tell us about where/when to add the knitted version.

**Comment by paul-buerkner** [comment]
After some discussions with Aki and some further changes, this vignette is ready to be included.
I will later move it to gh-pages in order to update the website accordingly.

**Comment by jgabry** [comment]
Thanks Paul!

**Pull request merged**
