### PR TITLE
prepare for v2.6.0

### PR DESCRIPTION
**Pull request by jgabry**
Branch for preparing the 2.6.0 release. @avehtari I will wait to merge this and do the release until the vignette in #210 is ready so that we can include it (I think it's almost ready). 

@LeeviLindgren This branch also includes a few minor changes to the `loo_predictive_metric` and `loo_[s]crps` functions that will be included in this release: 

* All of these functions now have a `cores` argument passed to `psis`
* `loo_[s]crps` : change `ll` argument to `log_lik` to match `loo_predictive_metric`

I think eventually we should also add a `psis_object` argument to these functions so that it's possible to avoid rerunning psis internally (see https://github.com/stan-dev/loo/issues/213) but we can do that in the future.

### CODE REVIEW

**Comment by jgabry** [comment]
@avehtari I think this release is ready. I'm about to be traveling for a few days, but I will submit to CRAN next week when I'm back. 

Draft of release notes: 

# loo v2.6.0

* New `loo_predictive_metric()` function for computing estimates of leave-one-out
predictive metrics: mean absolute error, mean squared error and root mean
squared error for continuous predictions, and accuracy and balanced accuracy for
binary classification. (#202, @LeeviLindgren)

* New functions `crps()`, `scrps()`, `loo_crps()`, and `loo_scrps()` for
computing the (scaled) continuously ranked probability score. (#203, @LeeviLindgren)

* New vignette "Mixture IS leave-one-out cross-validation for high-dimensional Bayesian models." This is a demonstration of the mixture estimators proposed in [Silva and Zanella (2022)](https://arxiv.org/abs/2209.09190).

**Comment by avehtari** [comment]
proposed in [Silva and Zanella (2022)](https://arxiv.org/abs/2209.09190). -> proposed by [Silva and Zanella (2022)](https://arxiv.org/abs/2209.09190).

**Comment by jgabry** [comment]
@avehtari I'm going to submit this release to CRAN and we can include #216 in the next release (we're still waiting on a few people). CRAN wants a release by April 1 (to fix a test that fails in an upcoming version of R) and I'm going to be pretty busy the next few days so I will submit it now.

**Comment by jgabry** [comment]
loo v2.6.0 is now on CRAN. I'm working on updating the loo website now

**Comment by avehtari** [comment]
Excellent!

**Pull request merged**
