### PR TITLE
Update normalizing constant of PSIS weights when moment matching

### PR DESCRIPTION
**Pull request by fweber144**
This fixes issue #166.

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks for the PR! Sorry for the delay in reviewing this. Looks good to me. @topipa?

**Review by jgabry — APPROVED** [review]

**Comment by topipa** [comment]
Looks good to me!

**Comment by jgabry** [comment]
Ok great, thanks @topipa, merging now. Thanks again @fweber144 for fixing this!

**Comment by fweber144** [comment]
No problem. Thanks for merging!

**Comment by fweber144** [comment]
Great to see the new CRAN release of loo, @jgabry ! However, I think the `NEWS` file now has a duplicated entry for the bug fixed by this PR. Shouldn't be a big problem, though. Just a bit confusing.

**Comment by jgabry** [comment]
Oh yeah you're right! I'll remove one of them

**Pull request merged**
